[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SUPABASE_URL = "https://modern-dashboard.supabase.co"
  VITE_APP_SUPABASE_URL = "https://modern-dashboard.supabase.co"
  GCLOUD_PROJECT_ID = ""
  GCLOUD_BUCKET = "modern-dashboard-metrics"
  ENABLE_MONITORING = "true"
  RATE_LIMIT_ENABLED = "true"

[dev]
  framework = "vite"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  external_node_modules = ["@supabase/supabase-js", "@google-cloud/storage"]
  node_bundler = "esbuild"
