steps:
  # Install dependencies
  - name: "node:18"
    entrypoint: npm
    args: ["ci"]

  # Run tests
  - name: "node:18"
    entrypoint: npm
    args: ["test"]
    env:
      - "CI=true"

  # Run type checking
  - name: "node:18"
    entrypoint: npm
    args: ["run", "type-check"]

  # Build the application
  - name: "node:18"
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "VITE_SUPABASE_URL=${_SUPABASE_URL}"
      - "VITE_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}"
      - "VITE_GCLOUD_PROJECT_ID=${PROJECT_ID}"
      - "VITE_GCLOUD_REGION=${_GCLOUD_REGION}"

  # Build and push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
      - "."

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
      - "--region"
      - "${_GCLOUD_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

substitutions:
  _SERVICE_NAME: "modern-dashboard"
  _GCLOUD_REGION: "us-central1"
  _SUPABASE_URL: "your-supabase-url"
  _SUPABASE_ANON_KEY: "your-supabase-anon-key"

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"

options:
  logging: CLOUD_LOGGING_ONLY
