apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-dashboard
  labels:
    app: modern-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modern-dashboard
  template:
    metadata:
      labels:
        app: modern-dashboard
    spec:
      containers:
        - name: modern-dashboard
          image: gcr.io/${PROJECT_ID}/modern-dashboard
          ports:
            - containerPort: 8080
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: supabase-url
            - name: VITE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: supabase-anon-key
            - name: VITE_GCLOUD_PROJECT_ID
              value: ${PROJECT_ID}
            - name: VITE_GCLOUD_REGION
              value: us-central1
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: modern-dashboard-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: modern-dashboard

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: modern-dashboard-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: modern-dashboard
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
